#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ghostty
mkdir -p $HOME/.config/ghostty
rm -rf $HOME/.config/ghostty/config
ln -s $DOTFILES/ghostty/config $HOME/.config/ghostty/config
